import { Component,OnInit} from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { QuizService } from 'src/app/services/quiz.service';

@Component({
  selector: 'app-load-quiz',
  templateUrl: './load-quiz.component.html',
  styleUrls: ['./load-quiz.component.css']
})
export class LoadQuizComponent implements OnInit{

  cId=0;
  quizzes=[
    {
      quizid:2,
      title:'',
      discription:'',
      noOfQuestion:'',
      maxmarks:'',
      category:{
        cid:21,
        title:''
      }
    }
  ];
  constructor(private _rout:ActivatedRoute,private _quiz:QuizService){}
  ngOnInit(): void {
   this.cId= this._rout.snapshot.params['cid'];
   this._rout.params.subscribe((params)=>{
    this.cId=params['cid'];
    if(this.cId==0){
 
      console.log('Load all the quiz');
      this._quiz.getActiveQuizzes().subscribe(
        (data:any)=>{
          this.quizzes=data
        },
        (error)=>{
          alert('error generated by server');
        }
      )
    }else{
      console.log('load single quiz')
      this._quiz.getCategorybyActive(this.cId).subscribe(
        (data :any)=>{
          this.quizzes=data
        },
        (error)=>{
          alert('error from the loading single category quizzes')
        }
      )
    }
   });
  
  
}

}
